name: juvia
version: "3.8"

networks:
  traefik: {}
  
services:
  # ! ---------------------
  # ! Traefik
  # ! ---------------------
  traefik:
    command:
      # Proivders
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=traefik
      # Entrypoints - HTTP
      - --entrypoints.http.address=:${TRAEFIK_HTTP_PORT:?}
      - --entrypoints.http.http.redirections.entrypoint.to=https
      - --entrypoints.http.http.redirections.entrypoint.scheme=https
      - --entrypoints.http.http.redirections.entrypoint.permanent=true
      # Entrypoints - HTTPS
      - --entrypoints.https.address=:${TRAEFIK_HTTPS_PORT:?}
      - --entrypoints.https.http.tls.certresolver=cloudflare
      - --entrypoints.https.http.tls.domains[0].main=${DOMAIN:?}
      - --entrypoints.https.http.tls.domains[0].sans=*.${DOMAIN:?},*.*.${DOMAIN:?}
      # Certresolvers - Cloudflare
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.email=${TRAEFIK_ACME_EMAIL:?}"
      - --certificatesresolvers.cloudflare.acme.storage=/data/acme-cloudflare.json
      - --certificatesresolvers.cloudflare.acme.caserver=${TRAEFIK_ACME_CASERVER:?}"
      # Logs
      - --log.level=INFO
      - --accesslog=true
      - --accesslog.filepath=/logs/access.log
      # Dashboard
      - --ping
      - --api=true
      - --api.dashboard=true
      # Global
      - --global.checknewversion=false
      - --global.sendanonymoususage=false
    environment:
      CF_API_EMAIL: ${TRAEFIK_CLOUDFLARE_API_EMAIL:?}
      CF_DNS_API_TOKEN: ${TRAEFIK_CLOUDFLARE_API_TOKEN:?}
      CF_ZONE_API_TOKEN: ${TRAEFIK_CLOUDFLARE_API_TOKEN:?}
    image: traefik:v2.8.3
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.rule: Host(`traefik.${DOMAIN:?}`)
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.middlewares: traefik-auth@docker
      # Middleware
      traefik.http.middlewares.traefik-auth.basicauth.users: ${TRAEFIK_BASICAUTH_USERS:?}
      traefik.http.middlewares.traefik-auth.basicauth.removeHeader: true
    networks:
      - traefik
    ports:
      - ${TRAEFIK_HTTP_PORT:?}:${TRAEFIK_HTTP_PORT:?}
      - ${TRAEFIK_HTTPS_PORT:?}:${TRAEFIK_HTTPS_PORT:?}
    restart: on-failure
    volumes:
      - /home/juvia/juvia/data/traefik:/data
      - /home/juvia/juvia/logs/traefik:/logs
  # ! ---------------------
  # ! Minio
  # ! ---------------------
  minio:
    command: [server, --console-address, :9001, /data]
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:?}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD?}
      MINIO_SERVER_URL: https://minio.${DOMAIN:?}
      MINIO_BROWSER_REDIRECT_URL: "https://console.minio.${DOMAIN}"
    image: minio/minio:RELEASE.2022-09-07T22-25-02Z.fips
    labels:
      traefik.enable: true
      traefik.http.routers.minio.entrypoints: https
      traefik.http.routers.minio.rule: Host(`minio.${DOMAIN:?}`) || Host(`cdn.${DOMAIN:?}`)
      traefik.http.routers.minio.service: minio
      traefik.http.services.minio.loadbalancer.server.port: 9000
      # Minio Console / Dashboard
      traefik.http.routers.minio-console.entrypoints: https
      traefik.http.routers.minio-console.rule: Host(`console.minio.${DOMAIN:?}`)
      traefik.http.routers.minio-console.service: minio-console
      traefik.http.services.minio-console.loadbalancer.server.port: 9001
    networks:
      - traefik
    restart: on-failure
    volumes:
      - /home/juvia/juvia/data/minio:/data