name: juvia
version: '3.8'

networks:
  registry:
    name: registry
  traefik:
    name: traefik

services:
  # ! ---------------------
  # ! Traefik
  # ! ---------------------
  traefik:
    command:
      # Proivders
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=traefik
      # Entrypoints - HTTP
      - --entrypoints.http.address=:${TRAEFIK_HTTP_PORT:?}
      - --entrypoints.http.http.redirections.entrypoint.to=https
      - --entrypoints.http.http.redirections.entrypoint.scheme=https
      - --entrypoints.http.http.redirections.entrypoint.permanent=true
      # Entrypoints - HTTPS
      - --entrypoints.https.address=:${TRAEFIK_HTTPS_PORT:?}
      - --entrypoints.https.http.tls.certresolver=cloudflare
      - --entrypoints.https.http.tls.domains[0].main=${DOMAIN:?}
      - --entrypoints.https.http.tls.domains[0].sans=*.${DOMAIN:?}
      # Certresolvers - Cloudflare
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.email=${TRAEFIK_ACME_EMAIL:?}
      - --certificatesresolvers.cloudflare.acme.storage=/data/acme-cloudflare.json
      - --certificatesresolvers.cloudflare.acme.caserver=${TRAEFIK_ACME_CASERVER:?}
      # Logs
      - --log.level=INFO
      - --accesslog=true
      - --accesslog.filepath=/logs/access.log
      # Dashboard
      - --ping
      - --api=true
      - --api.dashboard=true
      # Global
      - --global.checknewversion=false
      - --global.sendanonymoususage=false
    environment:
      CF_API_EMAIL: ${TRAEFIK_CLOUDFLARE_API_EMAIL:?}
      CF_DNS_API_TOKEN: ${TRAEFIK_CLOUDFLARE_API_TOKEN:?}
      CF_ZONE_API_TOKEN: ${TRAEFIK_CLOUDFLARE_API_TOKEN:?}
    image: traefik:v2.9.6
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.rule: Host(`traefik.${DOMAIN:?}`)
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.middlewares: traefik-auth@docker
      # Middleware
      traefik.http.middlewares.traefik-auth.basicauth.users: ${TRAEFIK_BASICAUTH_USERS:?}
      traefik.http.middlewares.traefik-auth.basicauth.removeHeader: true
    networks:
      - traefik
    ports:
      - ${TRAEFIK_HTTP_PORT:?}:${TRAEFIK_HTTP_PORT:?}
      - ${TRAEFIK_HTTPS_PORT:?}:${TRAEFIK_HTTPS_PORT:?}
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/juvia/juvia/data/traefik:/data
      - /home/juvia/juvia/logs/traefik:/logs
  # ! ---------------------
  # ! Portainer
  # ! ---------------------
  portainer:
    image: portainer/portainer-ce:2.16.2
    labels:
      traefik.enable: true
      traefik.http.routers.portainer.entrypoints: https
      traefik.http.routers.portainer.rule: Host(`portainer.${DOMAIN:?}`)
      traefik.http.services.portainer.loadbalancer.server.port: 9000
    networks:
      - traefik
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/juvia/juvia/data/portainer:/data
  # ! ---------------------
  # ! Registry
  # ! ---------------------
  registry:
    image: registry:2
    networks:
      - registry
    restart: on-failure
    labels:
      traefik.enable: false
    volumes:
      - /home/juvia/juvia/config/registry/config.yml:/etc/docker/registry/config.yml
      - /home/juvia/juvia/data/registry:/var/lib/registry
  registry-ui:
    environment:
      REGISTRY_URL: registry:5000
      REGISTRY_TITLE: ${DOMAIN:?}
      PULL_URL: registry.${DOMAIN:?}
      DELETE_IMAGES: true
      SINGLE_REGISTRY: true
      NGINX_PROXY_PASS_URL: http://registry:5000
    image: registry:2
    networks:
      - registry
    restart: on-failure
    labels:
      traefik.enable: true
      traefik.http.routers.registry.entrypoints: https
      traefik.http.routers.registry.rule: Host(`registry.${DOMAIN:?}`)
      traefik.http.routers.registry.middlewares: registry-auth@docker
      # Middleware
      traefik.http.middlewares.registry-auth.basicauth.users: ${REGISTRY_BASICAUTH_USERS:?}
      traefik.http.middlewares.registry-auth.basicauth.removeHeader: true
