# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

version: "3.8"

services:
  pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:?}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:?}
    image: dpage/pgadmin4:8.2
    labels:
      traefik.enable: true
      traefik.http.routers.pgadmin.entrypoints: https
      traefik.http.routers.pgadmin.rule: Host(`pgadmin.${DOMAIN:?}`)
    networks:
      - pgadmin
      - traefik
    restart: on-failure
    user: root
    volumes:
      - ../data/pgadmin:/var/lib/pgadmin
