# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

version: "3.8"

services:
  portainer:
    environment:
      PORTAINER_LICENSE_KEY: ${PORTAINER_LICENSE_KEY:?}
    image: portainer/portainer-ee:2.19.4
    labels:
      traefik.enable: true
      traefik.http.routers.portainer.entrypoints: https
      traefik.http.routers.portainer.rule: Host(`portainer.${DOMAIN:?}`)
      traefik.http.services.portainer.loadbalancer.server.port: 9000
    networks:
      - traefik
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../data/portainer:/data
