# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

version: "3.8"

services:
  whoami:
    image: traefik/whoami:v1.10.1
    labels:
      traefik.enable: true
      traefik.http.routers.whoami.entrypoints: https
      traefik.http.routers.whoami.rule: Host(`whoami.${DOMAIN:?}`)
    networks:
      - traefik
    restart: on-failure
