name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - config/**
      - services/**
      - docker-compose.networks.yaml
      - docker-compose.yaml
      - .github/workflows/deploy.yaml
  workflow_dispatch: {}

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Live
    steps:
      - id: deployment
        name: Create GitHub deployment
        uses: bobheadxi/deployments@v1
        with:
          env: Live
          step: start
          token: ${{ github.token }}
      - name: Deploy Compose stack to ${{ steps.deployment.outputs.env }}.
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_USER_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/juvia
            echo ${{ secrets.SSH_USER_PASSWORD }} | sudo -kS docker compose down
            git pull
            echo ${{ secrets.SSH_USER_PASSWORD }} | sudo -kS docker compose up -d
          script_stop: true
      - name: Update GitHub deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env: ${{ steps.deployment.outputs.env }}
          status: ${{ job.status }}
          step: finish
          token: ${{ github.token }}
