name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: environment

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - id: deployment
        name: Create new GitHub deployment
        uses: bobheadxi/deployments@v1
        with:
          env: ${{ inputs.environment }}
          step: start
          token: ${{ github.token }}
      - name: Deploy Compose stack to ${{ steps.deployment.outputs.env }}
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          key: ${{ secrets.SSH_USER_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: cd ./juvia && ./scripts/juvia.sh deploy ${{ vars.DOCKER_SERVICES }}
          script_stop: true
      - name: Update GitHub Deployment status for ${{ steps.deployment.outputs.env }}
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env: ${{ steps.deployment.outputs.env }}
          status: ${{ job.status }}
          step: finish
          token: ${{ github.token }}
